//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiniuUpload.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QiniuUpload.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 .\Account.xml 的本地化字符串。
        /// </summary>
        internal static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败，请检查账号设置 的本地化字符串。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .\History.log 的本地化字符串。
        /// </summary>
        internal static string HistoryLog {
            get {
                return ResourceManager.GetString("HistoryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .\Images 的本地化字符串。
        /// </summary>
        internal static string ImageSavePathDir {
            get {
                return ResourceManager.GetString("ImageSavePathDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有上传，请上传后再复制 的本地化字符串。
        /// </summary>
        internal static string NoUrlMessage {
            get {
                return ResourceManager.GetString("NoUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 的本地化字符串。
        /// </summary>
        internal static string ResultMessage {
            get {
                return ResourceManager.GetString("ResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功 的本地化字符串。
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传中，请稍候... 的本地化字符串。
        /// </summary>
        internal static string UpLoading {
            get {
                return ResourceManager.GetString("UpLoading", resourceCulture);
            }
        }
    }
}
